### ISSUE TITLE
Could not pass event InventoryClickEvent to dtlTraders v6.4.15

### ISSUE THREAD

**Issue by Togglerine** [MineVid/dtlTraders-plus-#18]
Hello,

I know dtltraders doesn't support 1.19.2 fully yet, but apart from problem described below everything works properly.

I can't change items price for sell in npc shop from citizens

[13:29:48 ERROR]: Could not pass event InventoryClickEvent to dtlTraders v6.4.15
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.PlayerInventory net.minecraft.server.level.EntityPlayer.fB()'
        at net.wesjd.anvilgui.version.Wrapper1_19_R1$AnvilContainer.<init>(Wrapper1_19_R1.java:98) ~[dtlTraders-6.4.15.jar:?]
        at net.wesjd.anvilgui.version.Wrapper1_19_R1.newContainerAnvil(Wrapper1_19_R1.java:91) ~[dtlTraders-6.4.15.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:176) ~[dtlTraders-6.4.15.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:164) ~[dtlTraders-6.4.15.jar:?]
        at net.wesjd.anvilgui.AnvilGUI.<init>(AnvilGUI.java:30) ~[dtlTraders-6.4.15.jar:?]
        at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:486) ~[dtlTraders-6.4.15.jar:?]
        at com.degitise.minevid.dtlTraders.guis.guiservices.ShopEditService.editItemPrice(ShopEditService.java:3360) ~[dtlTraders-6.4.15.jar:?]
        at com.degitise.minevid.dtlTraders.guis.guiservices.ShopEditService.access$5400(ShopEditService.java:34) ~[dtlTraders-6.4.15.jar:?]
        at com.degitise.minevid.dtlTraders.guis.guiservices.ShopEditService$19.onClick(ShopEditService.java:2115) ~[dtlTraders-6.4.15.jar:?]
        at com.degitise.minevid.dtlTraders.customInventory.DtlCustomInventoryService.onInventoryClickEvent(DtlCustomInventoryService.java:80) ~[dtlTraders-6.4.15.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1319.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1755]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3400) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1387) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1364) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1357) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1491) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1755]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

Greetings

**Comment by creptor** [comment]
I have the same issue with paper-mc 1.19.2 (#119). 

Basically, anything with the naming interface breaks the GUI, so it occurs when creating NPCs, stores, pages, defining prices, etc.

Everything else works, so I'm just sticking with the .yml for changes at the moment.

**Comment by MelonCraftDE** [comment]
same here, latest verison 6.4.16

AnvilGUI does not support server version "1_19_R1"

[19:36:02] [Server thread/ERROR]: Could not pass event InventoryClickEvent to dtlTradersPlus v6.4.16
java.lang.ExceptionInInitializerError: null
	at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:486) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.degitise.minevid.dtlTraders.d.b.b.d(ShopEditService.java:3360) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.degitise.minevid.dtlTraders.d.b.b.d(ShopEditService.java:34) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.degitise.minevid.dtlTraders.d.b.b$11.a(ShopEditService.java:2115) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.degitise.minevid.dtlTraders.b.b.a(DtlCustomInventoryService.java:80) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor502.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-133]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3312) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-133]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: AnvilGUI does not support server version "1_19_R1"
	at net.wesjd.anvilgui.version.VersionMatcher.a(VersionMatcher.java:34) ~[dtlTradersPlus-6.4.16.jar:?]
	at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[dtlTradersPlus-6.4.16.jar:?]
	... 27 more
Caused by: java.lang.ClassNotFoundException: net.wesjd.anvilgui.version.Wrapper1_19_R1
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at net.wesjd.anvilgui.version.VersionMatcher.a(VersionMatcher.java:28) ~[dtlTradersPlus-6.4.16.jar:?]
	at net.wesjd.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:35) ~[dtlTradersPlus-6.4.16.jar:?]
	... 27 more
[19:36:03] [Server thread/ERROR]: Could not pass event InventoryClickEvent to dtlTradersPlus v6.4.16
java.lang.NoClassDefFoundError: Could not initialize class net.wesjd.anvilgui.AnvilGUI
	at net.wesjd.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:486) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.degitise.minevid.dtlTraders.d.b.b.d(ShopEditService.java:3360) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.degitise.minevid.dtlTraders.d.b.b.d(ShopEditService.java:34) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.degitise.minevid.dtlTraders.d.b.b$11.a(ShopEditService.java:2115) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.degitise.minevid.dtlTraders.b.b.a(DtlCustomInventoryService.java:80) ~[dtlTradersPlus-6.4.16.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor502.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-133]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3312) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1361) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1338) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1331) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1309) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1197) ~[paper-1.19.2.jar:git-Paper-133]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-133]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
