### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by JellyBearAI** [MineVid/dtlTraders-plus-#23]
When reading the console I found this row of errors, how can I solve this?

[10:45:47] [Server thread/WARN]: [org.bukkit.craftbukkit.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[10:45:47] [Server thread/WARN]: java.lang.Exception
[10:45:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.legacy.CraftLegacy.<clinit>(CraftLegacy.java:270)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.util.CraftMagicNumbers.fromLegacy(CraftMagicNumbers.java:244)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.deserialize(ItemStack.java:518)
[10:45:47] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[10:45:47] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:87)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:129)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:209)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:58)
[10:45:47] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:264)
[10:45:47] [Server thread/WARN]: 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:247)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:37)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:163)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:161)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:120)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:338)
[10:45:47] [Server thread/WARN]: 	at dtlTraders-6.4.28.jar//com.degitise.minevid.dtlTraders.data.configs.Config.reload(Config.java:198)
[10:45:47] [Server thread/WARN]: 	at dtlTraders-6.4.28.jar//com.degitise.minevid.dtlTraders.data.configs.Config.get(Config.java:184)
[10:45:47] [Server thread/WARN]: 	at dtlTraders-6.4.28.jar//com.degitise.minevid.dtlTraders.Main.getConfig(Main.java:377)
[10:45:47] [Server thread/WARN]: 	at dtlTraders-6.4.28.jar//com.degitise.minevid.dtlTraders.Main.onEnable(Main.java:124)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[10:45:47] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[10:45:47] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629)
[10:45:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578)
[10:45:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752)
[10:45:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:514)
[10:45:47] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327)
[10:45:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219)
[10:45:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[10:45:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by wolfebersahd** [comment]
Not sure looks like your configs are outdated. dtlTraders doesn't use legacy materials anymore. You might want to delete the configs and let dtlTraders regenerate then off a fresh install
